import xarray as xr
import numpy as np


# General parmeters
num_of_frames = 1000
x_pix, y_pix = 1024, 1024
num_of_corr_steps = 50

def gen_data(filepath, num_of_rois):
        # Generate mock data
        fps = 15.24
        linerate = 7930.
        twod_projection = np.random.random((x_pix, y_pix))
        roi_coords = np.random.random((num_of_rois, 4))  # dims: coord_id X [x, y, width, height]
        result_corr_fit = np.random.random((num_of_rois, num_of_frames, num_of_corr_steps))  # we marked this array as a 4D array
                                                                                        # during our meeting, but it's
                                                                                        # actually a 3D array
        # ...

        # Start forming the Dataset
        # Data variables are real measurements or results that are generated by our different computations
        data_vars = {'twod_projection': (['x', 'y'], twod_projection),
                     'result_corr_fit': (['roi', 'time', 'steps'], result_corr_fit),
                     'linerate': linerate,}

        # Coordinates are labels for all data points
        coords = {'x': np.arange(x_pix), 'y': np.arange(y_pix),
                  'roi': np.arange(num_of_rois), 'time': np.arange(num_of_frames),
                  'steps': np.arange(num_of_corr_steps),
                  'fps': fps,
                  'filepath': filepath,
                  'param_fit': (['w0', 'NA'], [[5], [0.95]])}

        ds = xr.Dataset(data_vars, coords)
        return ds

ds1 = gen_data('xx.y', 12)
print(ds1)
ds2 = gen_data('ff.c', 22)

ds3_cat = xr.concat([ds1, ds2], dim='filepath')
print(ds3_cat)

print(ds3_cat.sel(filepath='xx.y', roi=14))

